<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SumberInformasi extends Model
{
    use HasFactory;

    protected $table = 'sumber_informasi';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'jenis_sumber',
    ];

    public function keputusanInformasi()
    {
        // Relasi hasMany jika satu sumber informasi dimiliki oleh banyak keputusan informasi
        return $this->hasMany(KeputusanInformasi::class, 'sumber_informasi_id', 'id');
    }

    public static $sumbers = [
        "Dinas Komunikasi dan Informatika - Kepala Dinas Komunikasi dan Informatika Kota Bogor",
        "Wali Kota Bogor - PJ Wali Kota Bogor",
        "Wakil Wali Kota Bogor - Wakil Wali Kota Bogor",
        "Sekretariat Daerah Kota Bogor - Sekretaris Daerah Kota Bogor",
        "Sekretariat Daerah Kota Bogor - Kepala Bagian Organisasi Sekda Kota Bogor",
        "Sekretariat Daerah Kota Bogor - Kepala Bagian Umum Kota Bogor",
        "Sekretariat Daerah Kota Bogor - Kepala Bagian Protokol dan Komunikasi Pimpinan",
        "Sekretariat Daerah Kota Bogor - Kepala Bagian Hukum dan Hak Asasi Manusia",
        "Sekretariat Daerah Kota Bogor - Kepala Bagian Pemerintahan",
        "Sekretariat Daerah Kota Bogor - Kepala Bagian Kesejahteraan Rakyat",
        "Sekretariat Daerah Kota Bogor - Kepala Bagian Administrasi Pembangunan",
        "Sekretariat Daerah Kota Bogor - Plh. Kepala Bagian Pengadaan Barang dan Jasa",
        "Sekretariat Daerah Kota Bogor - Kepala Bagian Perekonomian",
        "Sekretariat Daerah Kota Bogor - Asisten Perekonomian dan Pembangunan",
        "Sekretariat Daerah Kota Bogor - Asisten Pemerintahan dan Kesejahteraan Rakyat",
        "Sekretariat Daerah Kota Bogor - Asisten Administrasi Umum",
        "Sekretariat Daerah Kota Bogor - Staf Ahli Wali Kota Bidang Kemasyarakatan dan Sumber Daya Manusia",
        "Sekretariat Daerah Kota Bogor - Staf Ahli Wali Kota Bidang Ekonomi, Keuangan dan Pembangunan",
        "Sekretariat Daerah Kota Bogor - Staf Ahli Wali Kota Bidang Pemerintahan, Hukum dan Politik",
        "Sekretariat Daerah Kota Bogor - Sekretaris Daerah Kota Bogor",
        "Inspektorat Daerah - Inspektur Daerah Kota Bogor",
        "Sekretariat Dewan Perwakilan Rakyat Daerah - Sekretaris DPRD Kota Bogor",
        "Sekretariat KPU - Sekretaris KPU Kota Bogor",
        "Badan Keuangan dan Aset Daerah - Kepala Badan Keuangan dan Aset Daerah Kota Bogor",
        "Badan Pendapatan Daerah - Kepala Badan Pendapatan Daerah",
        "Badan Perencanaan Pembangunan, Riset dan Inovasi Daerah - Kepala Badan Perencanaan Pembangunan, Riset dan Inovasi Daerah",
        "Badan Kesatuan Bangsa Dan Politik - Kepala Badan Kesatuan Bangsa dan Politik",
        "Badan Kepegawaian dan Pengembangan Sumber Daya Manusia - Kepala Badan Kepegawaian dan Pengembangan Sumber Daya Manusia",
        "Badan Penanggulangan Bencana Daerah - Kepala Pelaksana Badan Penanggulangan Bencana Daerah",
        "Dinas Pariwisata dan Kebudayaan - Kepala Dinas Pariwisata dan Kebudayaan",
        "Dinas Pemuda dan Olahraga - Kepala Dinas Pemuda dan Olahraga",
        "Dinas Pendidikan - Kepala Dinas Pendidikan",
        "Dinas Lingkungan Hidup - Kepala Dinas Lingkungan Hidup",
        "Dinas Pemberdayaan Perempuan dan Perlindungan Anak - Kepala Dinas Pemberdayaan Perempuan dan Perlindungan Anak",
        "Dinas Ketahanan Pangan dan Pertanian - Kepala Dinas Ketahanan Pangan dan Pertanian Kota Bogor",
        "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu - Kepala Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu",
        "Dinas Arsip dan Perpustakaan - Kepala Dinas Arsip dan Perpustakaan",
        "Dinas Perdagangan dan Perindustrian - Kepala Dinas Perdagangan dan Perindustrian",
        "Dinas Pekerjaan Umum dan Penataan Ruang - Kepala Dinas Pekerjaan Umum dan Penataan Ruang",
        "Dinas Kesehatan - Kepala Dinas Kesehatan",
        "Dinas Perhubungan - Kepala Dinas Perhubungan",
        "Dinas Kependudukan dan Pencatatan Sipil - Kepala Dinas Kependudukan dan Pencatatan Sipil Kota Bogor",
        "Dinas Perumahan dan Permukiman - Kepala Dinas Perumahan dan Permukiman",
        "Dinas Sosial - Kepala Dinas Sosial",
        "Satuan Polisi Pamong Praja - Kepala Satuan Polisi Pamong Praja",
        "Dinas Tenaga Kerja - Kepala Dinas Tenaga Kerja",
        "Dinas Pengendalian Penduduk dan Keluarga Berencana Kota Bogor - Kepala Dinas Pengendalian Penduduk dan Keluarga Berencana Kota Bogor",
        "Dinas Pemadam Kebakaran dan Penyelamatan - Kepala Dinas Pemadam Kebakaran dan Penyelamatan",
        "Dinas Koperasi, Usaha Kecil dan Menengah, Perdagangan dan Perindustrian - Kepala Dinas Koperasi, Usaha Kecil, Menengah, Perdagangan dan Perindustrian",
        "Kelurahan Balumbang Jaya - Lurah Balumbang Jaya",
        "Kecamatan Bogor Tengah - Camat Bogor Tengah",
        "Kecamatan Bogor Selatan - Camat Bogor Selatan",
        "Kecamatan Bogor Barat - Camat Bogor Barat",
        "Kecamatan Bogor Utara - Camat Bogor Utara",
        "Kecamatan Bogor Timur - Camat Bogor Timur",
        "Kecamatan Tanah Sareal - Camat Tanah Sareal",
        "Kelurahan Kedung Halang - Lurah Kedung Halang",
        "Kelurahan Kertamaya - Lurah Kertamaya",
        "Kelurahan Pasir Jaya - Lurah Pasir Jaya",
        "Kelurahan Ciparigi - Lurah Ciparigi",
        "Kelurahan Menteng - Lurah Menteng",
        "Kelurahan Marga Jaya - Lurah Marga Jaya",
        "Kelurahan Harjasari - Lurah Harjasari",
        "Kelurahan Loji - Lurah Loji",
        "Kelurahan Cimahpar - Lurah Cimahpar",
        "Kelurahan Muarasari - Lurah Muarasari",
        "Kelurahan Ciluar - Lurah Ciluar",
        "Kelurahan Gunung Batu - Lurah Gunung Batu",
        "Kelurahan Genteng - Lurah Genteng",
        "Kelurahan Panaragan - Lurah Panaragan",
        "Kelurahan Bubulak - Lurah Bubulak",
        "Kelurahan Paledang - Lurah Paledang",
        "Kelurahan Empang - Lurah Empang",
        "Kelurahan Curug - Lurah Curug",
        "Kelurahan Curug Mekar - Lurah Curug Mekar",
        "Kelurahan Cibuluh - Lurah Cibuluh",
        "Kelurahan Cilendek Timur - Lurah Cilendek Timur",
        "Kelurahan Sempur - Lurah Sempur",
        "Kelurahan Rancamaya - Lurah Rancamaya",
        "Kelurahan Sindangsari - Lurah Sindangsari",
        "Kelurahan Katulampa - Lurah Katulampa",
        "Kelurahan Pakuan - Lurah Pakuan",
        "Kelurahan Sindangrasa - Lurah Sindangrasa",
        "Kelurahan Pamoyanan - Lurah Pamoyanan",
        "Kelurahan Kebon Kalapa - Lurah Kebon Kalapa",
        "Kelurahan Pasir Kuda - Lurah Pasir Kuda",
        "Kelurahan Lawanggintung - Lurah Lawanggintung",
        "Kelurahan Ranggamekar - Lurah Ranggamekar",
        "Kelurahan Tanah Baru - Lurah Tanah Baru",
        "Kelurahan Pasir Mulya - Lurah Pasir Mulya",
        "Kelurahan Semplak - Lurah Semplak",
        "Kelurahan Tegal Gundil - Lurah Tegal Gundil",
        "Kelurahan Sindangbarang - Lurah Sindang Barang",
        "Kelurahan Situgede - Lurah Situ Gede",
        "Kelurahan Baranangsiang - Lurah Baranangsiang",
        "Kelurahan Mulyaharja - Lurah Mulyaharja",
        "Kelurahan Pabaton - Lurah Pabaton",
        "Kelurahan Bantarjati - Lurah Bantarjati",
        "Kelurahan Bojongkerta - Lurah Bojongkerta",
        "Kelurahan Cikaret - Lurah Cikaret",
        "Kelurahan Cilendek Barat - Lurah Cilendek Barat",
        "Kelurahan Ciwaringin - Lurah Ciwaringin",
        "Kelurahan Babakan - Lurah Babakan",
        "Kelurahan Cibogor - Lurah Cibogor",
        "Kelurahan Tajur - Lurah Tajur",
        "Kelurahan Sukasari - Lurah Sukasari",
        "Kelurahan Cibadak - Lurah Cibadak",
        "Kelurahan Kayumanis - Lurah Kayumanis",
        "Kelurahan Kebonpedes - Lurah Kebon Pedes",
        "Kelurahan Kedung Badak - Lurah Kedung Badak",
        "Kelurahan Kedung Jaya - Lurah Kedung Jaya",
        "Kelurahan Kencana - Lurah Kencana",
        "Kelurahan Mekarwangi - Lurah Mekarwangi",
        "Kelurahan Sukadamai - Lurah Sukadamai",
        "Kelurahan Sukaresmi - Lurah Sukaresmi",
        "Kelurahan Tanah Sareal - Lurah Tanah Sareal",
        "Kelurahan Cipaku - Lurah Cipaku",
        "Kelurahan Babakan Pasar - Lurah Babakan Pasar",
        "Kelurahan Gudang - Lurah Gudang",
        "Kelurahan Tegallega - Lurah Tegallega",
        "Kelurahan Bondongan - Lurah Bondongan",
        "Kelurahan Kedung Waringin - Lurah Kedung Waringin",
        "Kelurahan Batutulis - Lurah Batutulis",
        "Rumah Sakit Umum Daerah Kota Bogor - Direktur RSUD Kota Bogor",
        "UPTD Puskesmas Tanah Sareal - Kepala UPTD Puskesmas Tanah Sareal",
        "UPTD Puskesmas Mulyaharja - Kepala UPTD Puskesmas Mulyaharja",
        "UPTD Puskesmas Kayumanis - Kepala UPTD Puskesmas Kayumanis",
        "UPTD Puskesmas Mekar Wangi - Kepala UPTD Puskesmas Mekar Wangi",
        "UPTD Puskesmas Kedung Badak - Kepala UPTD Puskesmas Kedung Badak",
        "UPTD Puskesmas Pondok Rumput - Kepala UPTD Puskesmas Pondok Rumput",
        "UPTD Puskesmas Gang Kelor - Kepala UPTD Puskesmas Gang Kelor",
        "UPTD Puskesmas Sindangbarang - Kepala UPTD Puskesmas Sindang Barang",
        "UPTD Puskesmas Pancasan - Kepala UPTD Puskesmas Pancasan",
        "UPTD Puskesmas Semplak - Kepala UPTD Puskesmas Semplak",
        "UPTD Puskesmas Pasir Mulya - Kepala UPTD Puskesmas Pasir Mulya",
        "UPTD Puskesmas Sempur - Kepala UPTD Puskesmas Sempur",
        "UPTD Puskesmas Belong - Kepala UPTD Puskesmas Belong",
        "UPTD Puskesmas Gang Aut - Kepala UPTD Puskesmas Gang Aut",
        "UPTD Puskesmas Merdeka - Kepala UPTD Puskesmas Merdeka",
        "UPTD Puskesmas Bogor Tengah - Kepala UPTD Puskesmas Bogor Tengah",
        "UPTD Puskesmas Tegal Gundil - Kepala UPTD Puskesmas Tegal Gundil",
        "UPTD Puskesmas Warung Jambu - Kepala UPTD Puskesmas Warung Jambu",
        "UPTD Puskesmas Bogor Utara - Kepala UPTD Puskesmas Bogor Utara",
        "UPTD Puskesmas Pulo Armyn - Kepala UPTD Puskesmas Pulo Armyn",
        "UPTD Puskesmas Bogor Timur - Kepala UPTD Puskesmas Bogor Timur",
        "UPTD Puskesmas Lawang Gintung - Kepala UPTD Puskesmas Lawang Gintung",
        "UPTD Puskesmas Bondongan - Kepala UPTD Puskesmas Bondongan",
        "UPTD Puskesmas Cipaku - Kepala UPTD Puskesmas Cipaku",
        "UPTD Puskesmas Bogor Selatan - Kepala UPTD Puskesmas Bogor Selatan",
        "UPTD Pemakaman Kelas A - Kepala UPTD Pemakaman",
        "UPTD Balai Latihan Kerja Kelas B - Kepala UPTD Balai Latihan Kerja",
        "UPTD Pengelolaan Air Limbah Kelas A - Kepala UPTD Pengelolaan Air Limbah",
        "UPTD Metrologi Legal Kelas A - Kepala UPTD Metrologi Legal",
        "UPTD Tempat Pemrosesan Akhir Sampah Kelas A - Kepala UPTD Tempat Pemrosesan Akhir Sampah",
        "UPTD Rumah Potong Hewan Terpadu Kelas A - Kepala UPTD Rumah Potong Hewan Terpadu",
        "UPTD Laboratorium Kesehatan Daerah - Kepala UPTD Labkesda",
        "UPTD Satuan Pendidikan Formal dan Non Formal Sejenis - Kepala UPTD Satuan Pendidikan Formal dan Non Formal Sejenis"
    ];
}
